import type { Metadata } from "next";
import Navbar from "../components/Navbar";
import "./globals.css";
import { Cormorant_Garamond } from "next/font/google";
import Footer from "@/components/Footer";

const cormorant = Cormorant_Garamond({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-cormorant",
});

export const metadata: Metadata = {
  title: "ZAZZMATAZ",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${cormorant.variable}`}>
      <body className="bg-[#FFF8F2]">
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
